services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: webhooked
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dummy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com  
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .server.env
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

volumes:
  postgres_data: